### ISSUE TITLE
Correctly install screensaver for Windows

### ISSUE THREAD

**Issue by gak** [gak/gravit#17]

**Comment by gak** [comment]
The installer scripts is in the old SVN repo somewhere. I'm going to dig it up soon.

@FrMo: Are you interested in handling the Windows builds buy any chance? I can get you the original installer files as soon as you let me know :)

**Comment by FrMo** [comment]
@gak: sure, i could the windows build, and check for compile problems from time to time.

About the installer: I am completely unexperienced with writing windows installers, but simply give me the files, and I will see if I can do it.

**Comment by gak** [comment]
@FrMo I've added the commit in 3fdabba

Please bear in mind it is an old installer, so it might not work first go, especially with those hardcoded absolute paths :)

The "Run" section has checkboxes for the last screen of the installer. I'm thinking we get rid of the option of editing gravit.cfg since the settings are more automatic now.

Also, I've been using "git flow" which helps organising certain git branches better. The main dev branch is now called "develop" and "master" will be the production/stable branch. See http://nvie.com/posts/a-successful-git-branching-model/ for a quick walkthrough.

I'll update the Wiki to reflect this information.

**Comment by gak** [comment]
#45 for updating the Wiki with the new branches.

**Comment by FrMo** [comment]
I am still wondering how to avoid spilling DLLs into windows\system32 (SDL, SDL_image, SDL_ttf, PNG, freetype, LUA, libgomp, pthread ..)

The normal search order for DLLs is described here: 
http://msdn.microsoft.com/en-us/library/7d83bc18.aspx
http://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx
http://lua-users.org/wiki/LoadLibrary

Some possible solutions:
- static linking (needs real static libraries), so all libs are contained in the executable
- register an application-specific search path in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\GRAVIT.scr
  (http://www.codeguru.com/cpp/w-p/dll/article.php/c99/Application-Specific-Paths-for-DLL-Loading.htm)
- add the folder containing the DLLs to the system PATH 
  (http://stackoverflow.com/questions/8283569/screen-saver-dependent-on-files-c)
- prefix all DLLs with "gravit_" (gravit_SDL.dll etc). Problem: how to tell winsows to use gravit_SDL.dll and not SDL.dll?
- not sure if this works: registering the screensaver from a different location (c:\program files\gravit instead of c:\windows)
- give up and put all DLLs into windows\sytem32

I you have any working solutions for me, please let me know.

**Comment by FrMo** [comment]
see also: issue #38 (SDL creates stdout.txt and stder.txt in the program directory)

**Comment by gak** [comment]
What about loading DLL's at runtime with the LoadLibrary function? http://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx

You can specify a full path to the DLL using the registry to search for the Gravit install path.

**Comment by FrMo** [comment]
The new windows installer works for me, both in 32bit and 64bit (XP/Vista/Win7). 

@gak : I think we should state a "feature-freeze" now, and quickly go for a release of what we have (in the current develop branch). Could you check the develop branch on OSX ?

**Comment by gak** [comment]
@FrMo Good idea. I'll make sure OS X is building and works. Give me a week though.

**Comment by FrMo** [comment]
@gak take your time :-) . 
Maybe you could also check the new windows installers; I have uploaded them to my github downloads area: https://github.com/FrMo/gravit/downloads

**Comment by gak** [comment]
Works perfectly on the 64bit version. :)
