### ISSUE TITLE
SCREENSAVER

### ISSUE THREAD

**Issue by alextricity** [gak/gravit#90]
Screensaver locks up after a period of time. Happens with the latest version on all computers. The systems have plenty of resources too. Overall, the systems are reliable.

The screensaver works great with pretty much any settings, but when it sits for a little while, the particles disappear and the program becomes unresponsive. Using only one core, and little memory it still happens. I suspect that maybe there is a scheduler thread AND computation thread running on the same core?.. the scheduler cant keep up and panics/dies/particles disappear. Does Gravit save logs?

**Comment by FrMo** [comment]
Hello alextricity,
Thank you for this interesting problem report.

There are actually two known "lock-up" problems that have been fixed in the current development branch already;
but I have observed them only on "slow graphics hardware" (i.e. intel coreI5 build-in graphics).

Before we go to the console log (stdout.txt), could you check if one of these workarounds fix your problem:
- edit gravit.cfg, and set "recordingvideorefreshtime 0" (original value is 30).
  reason: gravit is regularly refreshing the display (OSD) during a spawn operation.It sometimes happens that the videoupdate is so slow, that it happens too often (basially, after each new particle). recordingvideorefreshtime 0 disables this feature.
- edit gravit.cfg, and add the following line:
  "particlesizemax 63"
  reason: the default value in gravit 0.5.0 is much too big; when particles are very near (=big), you graphics card can take up to several seconds to draw video frames with big particles.

Please tell us if one of these has solved the problem, or not.

cheers,
   Frank.

**Comment by alextricity** [comment]
Oh, forgot to mention. This is a DUAL display setup with Gravit spanned across both. I am using integrated graphics on a DELL OPTIPLEX 790. 

It appears that both of these have fixed my issues. Thank you. I will let you know if it reoccurs. If you would like any more hardware information, please let me know.

Also, an FYI, I plan on rendering a few months of 4K resolution video with (10M?) particles. I MAY try to make it 3D, though I am not exactly sure if that is possible. I'll send a link on YouTube when it is complete. I have upgraded my computer recently so this will be much faster.  If you would like certain functions tested to their absolute extreme for bug detection, send me a config file. 
(current hardware 5.575GHZ (water cooled) - 8 cores - 32GB DDR3 2100MHZ - Radeon 7770 Graphics - (plenty TB) HDD)

THANK YOU for making/supporting Gravit! It's AMAZING!

**Comment by FrMo** [comment]
gravit 0.5.1 (to be release real soon now) fixes the problem.
